execution_engine: asyncio
logger:
  transports: [console]  # You can use [file, console] for both
  level: info
  path: "logs/mcp-agent.jsonl"  # Used for file transport
  # For dynamic log filenames:
  # path_settings:
  #   path_pattern: "logs/mcp-agent-{unique_id}.jsonl"
  #   unique_id: "timestamp"  # Or "session_id"
  #   timestamp_format: "%Y%m%d_%H%M%S"

mcp:
  servers:
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
    filesystem:
      command: "npx"
      args:
        [
          "-y",
          "@modelcontextprotocol/server-filesystem",
          "/Users/jing/Desktop/coding.../Agent/wechat-agent/Mcp_Agent/docs",
        ]
    baidu-search:
      command: "uvx"
      args: ["baidu-mcp-server"]

openai:
  # Secrets (API keys, etc.) are stored in an mcp_agent.secrets.yaml file which can be gitignored
  default_model: deepseek-v3-250324